const styleTypes = {
	width: null,
  height: null,
  borderRadius: null,
  backgroundColor: null,
  background: null,
  margin: null,
  marginTop: null,
  marginBottom: null,
  marginRight: null,
  marginLeft: null,
  padding: null,
  paddingLeft: null,
  paddingRight: null,
  paddingBottom: null,
  paddingTop: null,
  fontSize: null,
  color: null,
  display: null,
  flexDirection: null,
  alignItems: null,
  justifyContent: null,
  flex: null,
  cursor: null,
  textAlign: null,
	boxShadow: null,
}

export { styleTypes }
